# .streamlit/secrets.toml
[slack]
client_id = "80956966309.10458980552129"
client_secret = "8f986395ca3cacceccdf03fd02969a51"
redirect_uri = "http://localhost:8501"

# 자동가입 허용 도메인 리스트
[founders_email]
domains = ["thefounders.kr", "anua.kr"]

# 스노우플레이크 페어키
[snowflake]
key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmOr/nAnM1BXoO
bZYlc8Iz3RDU5wCPolct0LbqZV2HZCjmQf7U7eGIpnxjBKtP6y73yhi1s7cYJsxU
5o9BWW9L7jZ00w3NoLcLIh7sbbO1WjYvnIBaIWpDSF+euB3fRHzjGGTyvHlfBmin
6PxXdYFHH+d/Qo05RTLb4l8Mnptva57PiORMIf+Wmp5B0hCAfJNFTnr7xhgynyB/
VpBkRs2xvn3++TpW/okW1niDgCl1RRJZQ8LH+EVmatX+j+u2iWccR4hsn8RlrXJl
sxVEiOOAIy5k3gzw50xkfBWLrufcHopwaqT3aHo7b/VbsPuLGIvBBzzsR32HMApk
YGS1TfPhAgMBAAECggEAAR87L5L3I3s1a3gNg/79zKSGvil5aflx2pIgA5wiaz/M
958SikiugvdM4Rd4CfdJEG9k7C2MduQUpnOjBrE03fZQ4r1wXc7igLzhc0MLNsDh
5fTUct9KvgMPcP/LxPz2VZX9oPE5GxVHowSrYYeo/dRDHLtD6XhRn1VeDZS7ZnoD
V/4x2JlR3Om+YtOwFlU5po/McBD0VhDMzaFBW4n/OOlNtHTtRUSE/nVyHYW1rJ06
NDctyrcllVUFvVeFw89TMOKCdTbR2cD1PFoLXZ+qgFV2mZHT5dr10vemoFWlqV1A
XJuVyLkmUJob4QQcJ7rZPY22qvhcknLpQGX5Xqzr8QKBgQDX1tIVpYWOajx4K2D3
+8fQxA97rds+zdgYRqByfdvNYJyT2MEpgvW4wHW0xrkPoziiL97qR+LIluH24Rsy
6Ch95T/aQYkuQgUuJ3T6zN1eeY673jGcpEjK1DAK0Z4QQ+KwptIL7LpAGU85Ewrq
PSvepTlCSCnmhu7W7U5a4Vr4UQKBgQDFKNiovlCmz7wUCLoKUM1RFxeSeXG2MEOX
7gW8Ba5IeyvavCDPNi1KaXyPhrhmAyb1qZacixEhh44ije0IxEueTkq45uQ/mhrJ
iBi46nSgHgCfT0py0lylH+USV9Bv/zM+e3BqRrN2Nf5DqyV0waFpTEyXS8h+STIG
tl7E0CzukQKBgCUHEnVqNvZOnV8UOgdw5z+WUv2pvsIQeDD59M6PbuTV3Saz+bdQ
Yy01vzurF9Zp7u5L/hb9DBfTYqKCzbK3BzNJ3+Fmes03wEHBvRzFhniNrAHoxWQU
/vPk4PUKLu6lZr9dbw1iqDUU4nVtIeM7aUpB2AfZ724/2bt/bIDExmFxAoGASX6W
dSCsk+IwLA+suhew0Z+YC+P1fYK0T7hMrvA3LZGsoVcrq9J4Q5ra8e24Y16dcUoM
eMJmWmdblontaC00OwjYVeDMCOF7RtDS1mufmehVNw2ppO/B1VP0YkgVzQoGoi4F
k7hTQaeS5sqvpbxgXQ4yJtv7GwhR+6qT3S308eECgYBJwcDqQRMAvCuAei6gPuQG
JqIqbyvnrWHYxRPxR0+9+GszwcXDL2jCoOXOFbzskGG4gz3PZxalLMEDYURj2uwZ
KucldryGBMMTWnz3PIJA92sCLQf9P0dnv2sI2Sl6nFi+ryhtDLfeo7siv0Ytey/j
A7nHda2hbku0kg2jLQ9AHA==
-----END PRIVATE KEY-----"""